url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Metidia Advertising Solutions
email: contact@metidia.com
description: "Metidia Advertising Solutions (MAS) is the agency in charge to put your brand within the Metidia's game. As you know, Metidia develops video game with reality as forground. MAS is in charge to put your brand into the game."


# Team names, titles and social links
people:
- name: Oswald BERNARD
  pic: https://trello-attachments.s3.amazonaws.com/571fd4957671470585c75b62/200x219/ce82efaaaf06d0b4c9492229ea0665eb/1.png
  position: Lead Business Developer
  social:
    - title: envelope-o
      url: mailto:oswald.bernard@metidia.com

- name: Fanny GARRET
  pic: https://trello-attachments.s3.amazonaws.com/571fd4957671470585c75b62/200x219/591a183338b8a4948da5882886eea741/2.png
  position: Lead Marketer
  social:
    - title: envelope-o
      url: mailto:Fanny.garret@metidia.com

- name: Fabien BERNARD
  pic: https://trello-attachments.s3.amazonaws.com/571fd4957671470585c75b62/200x219/a01ba42f8a1d9d4091e6ca867445dec8/3.png
  position: Lead Developer Back-end
  social:
    - title: envelope-o
      url: mailto:fabien.bernard@metidia.com

- name: Nicolas CARLO
  pic: https://trello-attachments.s3.amazonaws.com/571fd4957671470585c75b62/200x219/699bf61f7e3004adcf36b3d044889fc8/4.png
  position: Lead Developer Front-end
  social:
    - title: envelope-o
      url: mailto:nicolas.carlo@metidia.com

- name: Maureen FRADON
  pic: https://trello-attachments.s3.amazonaws.com/571fd4957671470585c75b62/200x219/18e2564cd58f360fa76a8ecfcf5b9bed/5.png
  position: Lead Arts
  social:
    - title: envelope-o
      url: mailto:maureen.fradon@metidia.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope-o
    url: mailto:contact@metidia.com
# Postal address (add as many lines as necessary)
address:
  - line: 35 rue du sentier
  - line: 75002 Paris, France

# Build settings
markdown: kramdown
permalink: pretty
